In [1]:
import numpy as np

In [3]:
mylist = [1,2,3]
myarray = np.array(mylist)

In [4]:
print(myarray)

[1 2 3]


In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(shape = (5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
arr = np.random.randint(0,100,10)

In [9]:
arr

array([96, 97, 82, 12, 37, 56, 61, 92, 82, 12])

In [10]:
arr.max()

97

In [11]:
arr.argmax()

1

In [13]:
arr.min()

12

In [14]:
arr.argmin()

3

In [15]:
arr2 = np.arange(0,100).reshape(10,10)

In [16]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
arr2[1][6]

16

In [18]:
arr2[: ,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [19]:
arr2[0:4, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [20]:
arr2[0:4, 0:3] = 0

In [21]:
arr2

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  0,  0, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
ARR = arr2.copy()

In [25]:
ARR[:,1:3 ] = 999

In [26]:
ARR

array([[  0, 999, 999,   3,   4,   5,   6,   7,   8,   9],
       [  0, 999, 999,  13,  14,  15,  16,  17,  18,  19],
       [  0, 999, 999,  23,  24,  25,  26,  27,  28,  29],
       [  0, 999, 999,  33,  34,  35,  36,  37,  38,  39],
       [ 40, 999, 999,  43,  44,  45,  46,  47,  48,  49],
       [ 50, 999, 999,  53,  54,  55,  56,  57,  58,  59],
       [ 60, 999, 999,  63,  64,  65,  66,  67,  68,  69],
       [ 70, 999, 999,  73,  74,  75,  76,  77,  78,  79],
       [ 80, 999, 999,  83,  84,  85,  86,  87,  88,  89],
       [ 90, 999, 999,  93,  94,  95,  96,  97,  98,  99]])